### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by wjczf123** [GT-SALT/LADA#3]
Hi, I am not familiar with the NER. The download page (https://www.clips.uantwerpen.be/conll2003/ner/) looks a bit confusing. I found two dataset (https://github.com/kyzhouhzau/BERT-NER/tree/master/data and https://github.com/kamalkraj/BERT-NER/tree/dev/data) in their repositories. But the size seems different. Which data set should I use? Or can you upload the dataset?

**Comment by felixwzh** [comment]
The second one https://github.com/kamalkraj/BERT-NER/tree/dev/data

**Comment by wjczf123** [comment]
OK. Thank you very much!
