### ISSUE TITLE
BERT+Intra&Inter-LADA

### ISSUE THREAD

**Issue by wjczf123** [GT-SALT/LADA#4]
Can you tell me how to run BERT+Intra&Inter-LADA? Thank you a lot.

**Comment by felixwzh** [comment]
`--intra-mix-ratio 1` means intra-mix only, `--intra-mix-ratio 0` means inter-mix only. `--intra-mix-ratio` in (0,1) means we have `intra-mix-ratio` chance to do intra-mix and (1- `intra-mix-ratio`) chance to do inter mix.

**Comment by wjczf123** [comment]
If so, why --intra-mix-ratio is -1 in BERT+Inter-LADA?

**Comment by felixwzh** [comment]
sorry for the confusion, --intra-mix-ratio <=0 means inter-mix only.

**Comment by wjczf123** [comment]
OK. I get it. Thank you a lot.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GT-SALT/LADA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月15日(星期四) 晚上9:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [GT-SALT/LADA] BERT+Intra&amp;Inter-LADA (#4)





 
sorry for the confusion, --intra-mix-ratio <=0 means inter-mix only.
