### ISSUE TITLE
Some confuse on data augmentation part

### ISSUE THREAD

**Issue by hqp-hub** [GT-SALT/LADA#6]
Hi ,first thing first, thanks for your incredible work !
There still some qustion confused me, one of them is the data augmentation part, 
according to code, it seems that every original sentence is mixed with anothor sentence then count the loss to regulate model. 
It's more like add noise than data augmentation to me, cuz after augmentation, n sentence is still n sentence,
so i wanna figure out if the original sentence is used during training, thanks a lot !

**Comment by felixwzh** [comment]
Hi, thanks for your interest in our work. your understanding is correct, and that is what we intended to do. One thing to notice is that, after augmentation, there are still n sentences, but each sentence is somehow mixed with another sentence, which is helpful to training. 
About the original sentences, they are not directly used during training. They are all mixed before training.

**Comment by hqp-hub** [comment]
Thanks for your reply!
have a nice day
